/*
 * This source file was generated by the Gradle 'init' task
 */
package domain.model;

import domain.service.GameService;
import domain.service.GameServiceImpl;

public class App {


    public static void main(String[] args) {
        Game game=new Game();
        game.set(8,1);
        game.set(0,1);
        game.set(4,1);
        GameServiceImpl gs = new GameServiceImpl();
        System.out.println(gs.checkWin(game,1).toString());

    }
}
